version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    container_name: softy-pinko-back-end
    networks:
      - softy-pinko-network

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    container_name: softy-pinko-front-end
    depends_on:
      - back-end
    networks:
      - softy-pinko-network

networks:
  softy-pinko-network:
    driver: bridge
