version: '3'

services:
  front-end:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  back-end-1:
    image: python:3.8-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: python api.py
    ports:
      - "5252:5252"

  back-end-2:
    image: python:3.8-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: python api.py
    ports:
      - "5253:5252"

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
